package com.beeradviser;

import android.app.Activity;
import android.os.Bundle;
import android.view.View;
import android.widget.Spinner;
import android.widget.TextView;

import java.util.List;

public class FindBeerActivity extends Activity {
    @Override
    //gets called when the activity is first created
    //creates the activity
    //activity object is used to display the UI
    //activity object shows UI as defined in the activity_find_beer.xml file
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_find_beer);
    }

    //call when the user clicks on "Find Beer!!" Button
    public void onClickFindBeer(View view) {
        //R is a class automatically generated by Android Studio
        //R refers to the resources of the app

        //findViewByID returns a view object, we need to cast it to a TextView
        TextView brands = (TextView) findViewById(R.id.brands);
        Spinner color = (Spinner) findViewById(R.id.spinner);

        //get the beerBrands from the BeerExpert class
        List<String> brandsList = BeerExpert.getBrands(String.valueOf(color.getSelectedItem()));
        StringBuilder brandsFormatted = new StringBuilder();

        //append the brands to the string builder
        //add a new line after each brand
        //so that each brand is on a new line
        for(String brand : brandsList){
            brandsFormatted.append(brand).append("\n");
        }

        //set the text of the brands TextView to the brandsFormatted string
        brands.setText(brandsFormatted);
    }

}